---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  ubuntu-1404-x64_r1:
    default_apply_opts:
      strict_variables:
    roles:
      - default
      - router1
    platform: ubuntu-14.04-amd64
    hypervisor: docker
    image: ubuntu:14.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'rm /usr/sbin/policy-rc.d' 
      - 'rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl' 
      - 'apt-get update'
      - 'apt-get install -y net-tools wget dnsutils' 
      - 'locale-gen en_US.UTF-8'
      - 'sysctl net.ipv6.conf.all.disable_ipv6=0'
  ubuntu-1404-x64_r2:
    default_apply_opts:
      strict_variables:
    roles:
      - router2
    platform: ubuntu-14.04-amd64
    hypervisor: docker
    image: ubuntu:14.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'rm /usr/sbin/policy-rc.d' 
      - 'rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl' 
      - 'apt-get update'
      - 'apt-get install -y net-tools wget dnsutils' 
      - 'locale-gen en_US.UTF-8'
      - 'sysctl net.ipv6.conf.all.disable_ipv6=0'
  ubuntu-1404-x64_r3:
    default_apply_opts:
      strict_variables:
    roles:
      - router3
    platform: ubuntu-14.04-amd64
    hypervisor: docker
    image: ubuntu:14.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'rm /usr/sbin/policy-rc.d' 
      - 'rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl' 
      - 'apt-get update'
      - 'apt-get install -y net-tools wget dnsutils' 
      - 'locale-gen en_US.UTF-8'
      - 'sysctl net.ipv6.conf.all.disable_ipv6=0'
CONFIG:
  trace_limit: 200
  masterless: true
...
# vim: syntax=yaml
