fixtures:
    symlinks:
      routing: "#{source_dir}"
    repositories:
      stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
      tea: https://github.com/icann-dns/puppet-tea.git
      concat: https://github.com/puppetlabs/puppetlabs-concat
      inifile: https://github.com/puppetlabs/puppetlabs-inifile
      logrotate: https://github.com/icann-dns/puppet-logrotate
      quagga:
        repo: https://github.com/icann-dns/puppet-quagga.git
        ref: add_rejected_routes
      openbgpd:
        repo: https://github.com/icann-dns/puppet-openbgpd.git
        ref: add_rejected_routes
